// This file has been generated by the GUI designer. Do not modify.
namespace PdfWidget
{
    public partial class PdfWidget : Gtk.Bin
    {
        private Gtk.Box vbox1;
        private Gtk.Box hbox1;
        private Gtk.Button SaveButton;
        private Gtk.Button PrintButton;
        private Gtk.Button FirstPageButton;
        private Gtk.Button PreviousButton;
        private Gtk.Button NextButton;
        private Gtk.Button LastPageButton;
        private Gtk.SpinButton CurrentPage;
        private Gtk.Label PageCountLabel;
        private Gtk.ScrolledWindow scrolledwindow1;
        private Gtk.Box vboxImages;

        protected virtual void Build()
        {
            this.Name = "PdfWidget.PdfWidget";
            this.Visible = false;

            // VBox
            this.vbox1 = new Gtk.Box(Gtk.Orientation.Vertical, 6);
            this.vbox1.Name = "vbox1";

            // HBox
            this.hbox1 = new Gtk.Box(Gtk.Orientation.Horizontal, 6);
            this.hbox1.Name = "hbox1";

            // SaveButton
            this.SaveButton = new Gtk.Button(Gtk.Stock.Save);
            this.SaveButton.CanFocus = true;
            this.SaveButton.Name = "SaveButton";
            this.SaveButton.UseUnderline = true;
            this.SaveButton.Clicked += new System.EventHandler(this.OnSaveButtonClicked);
            this.hbox1.PackStart(this.SaveButton, false, false, 0);

            // PrintButton
            this.PrintButton = new Gtk.Button(Gtk.Stock.Print);
            this.PrintButton.CanFocus = true;
            this.PrintButton.Name = "PrintButton";
            this.PrintButton.UseUnderline = true;
            this.PrintButton.Clicked += new System.EventHandler(this.OnPrintButtonClicked);
            this.hbox1.PackStart(this.PrintButton, false, false, 0);

            // FirstPageButton
            this.FirstPageButton = new Gtk.Button(Gtk.Stock.GotoFirst);
            this.FirstPageButton.CanFocus = true;
            this.FirstPageButton.Name = "FirstPageButton";
            this.FirstPageButton.UseUnderline = true;
            this.FirstPageButton.Clicked += new System.EventHandler(this.OnFirstPageButtonClicked);
            this.hbox1.PackStart(this.FirstPageButton, false, false, 0);

            // PreviousButton
            this.PreviousButton = new Gtk.Button(Gtk.Stock.GoBack);
            this.PreviousButton.CanFocus = true;
            this.PreviousButton.Name = "PreviousButton";
            this.PreviousButton.UseUnderline = true;
            this.PreviousButton.Clicked += new System.EventHandler(this.OnPreviousButtonClicked);
            this.hbox1.PackStart(this.PreviousButton, false, false, 0);

            // NextButton
            this.NextButton = new Gtk.Button(Gtk.Stock.GoForward);
            this.NextButton.CanFocus = true;
            this.NextButton.Name = "NextButton";
            this.NextButton.UseUnderline = true;
            this.NextButton.Clicked += new System.EventHandler(this.OnNextButtonClicked);
            this.hbox1.PackStart(this.NextButton, false, false, 0);

            // LastPageButton
            this.LastPageButton = new Gtk.Button(Gtk.Stock.GotoLast);
            this.LastPageButton.CanFocus = true;
            this.LastPageButton.Name = "LastPageButton";
            this.LastPageButton.UseUnderline = true;
            this.LastPageButton.Clicked += new System.EventHandler(this.OnLastPageButtonClicked);
            this.hbox1.PackStart(this.LastPageButton, false, false, 0);

            // CurrentPage
            this.CurrentPage = new Gtk.SpinButton(0, 999999, 1);
            this.CurrentPage.CanFocus = true;
            this.CurrentPage.Name = "CurrentPage";
            this.CurrentPage.Adjustment.PageIncrement = 10;
            this.CurrentPage.ClimbRate = 1;
            this.CurrentPage.Numeric = true;
            this.CurrentPage.ValueChanged += new System.EventHandler(this.OnCurrentPageValueChanged);
            this.hbox1.PackStart(this.CurrentPage, false, false, 0);

            // PageCountLabel
            this.PageCountLabel = new Gtk.Label();
            this.PageCountLabel.Name = "PageCountLabel";
            this.hbox1.PackStart(this.PageCountLabel, false, false, 0);

            this.vbox1.PackStart(this.hbox1, false, false, 0);

            // ScrolledWindow
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = Gtk.ShadowType.In;

            // Viewport
            Gtk.Viewport viewport = new Gtk.Viewport();
            viewport.ShadowType = Gtk.ShadowType.None;

            // VBoxImages
            this.vboxImages = new Gtk.Box(Gtk.Orientation.Vertical, 6);
            this.vboxImages.Name = "vboxImages";

            viewport.Add(this.vboxImages);
            this.scrolledwindow1.Add(viewport);
            this.vbox1.PackStart(this.scrolledwindow1, true, true, 0);

            this.Add(this.vbox1);
            if (this.Child != null)
            {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
