
// This file has been generated by the GUI designer. Do not modify.
namespace PdfWidget
{
	public partial class PdfWidget
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button PreviousButton;
		private global::Gtk.Button NextButton;
		private global::Gtk.CheckButton ContinuousCheckBox;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.VBox vboxImages;
		private global::Gtk.Image image1;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PdfWidget.PdfWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PdfWidget.PdfWidget";
			// Container child PdfWidget.PdfWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.PreviousButton = new global::Gtk.Button ();
			this.PreviousButton.CanFocus = true;
			this.PreviousButton.Name = "PreviousButton";
			this.PreviousButton.UseUnderline = true;
			this.PreviousButton.Label = global::Mono.Unix.Catalog.GetString ("Previous Page");
			this.hbox1.Add (this.PreviousButton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.PreviousButton]));
			w1.Position = 2;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.NextButton = new global::Gtk.Button ();
			this.NextButton.CanFocus = true;
			this.NextButton.Name = "NextButton";
			this.NextButton.UseUnderline = true;
			this.NextButton.Label = global::Mono.Unix.Catalog.GetString ("Next Page");
			this.hbox1.Add (this.NextButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.NextButton]));
			w2.Position = 3;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ContinuousCheckBox = new global::Gtk.CheckButton ();
			this.ContinuousCheckBox.CanFocus = true;
			this.ContinuousCheckBox.Name = "ContinuousCheckBox";
			this.ContinuousCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Continuous Scroll");
			this.ContinuousCheckBox.Active = true;
			this.ContinuousCheckBox.DrawIndicator = true;
			this.ContinuousCheckBox.UseUnderline = true;
			this.hbox1.Add (this.ContinuousCheckBox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ContinuousCheckBox]));
			w3.Position = 4;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vboxImages = new global::Gtk.VBox ();
			this.vboxImages.Name = "vboxImages";
			this.vboxImages.Spacing = 6;
			// Container child vboxImages.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.vboxImages.Add (this.image1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxImages [this.image1]));
			w6.Position = 0;
			w5.Add (this.vboxImages);
			this.scrolledwindow1.Add (w5);
			this.vbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow1]));
			w9.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.PreviousButton.Clicked += new global::System.EventHandler (this.OnPreviousButtonClicked);
			this.NextButton.Clicked += new global::System.EventHandler (this.OnNextButtonClicked);
			this.ContinuousCheckBox.Clicked += new global::System.EventHandler (this.OnContinuousCheckBoxClicked);
		}
	}
}
