// This file has been generated by the GUI designer. Do not modify.
using DtronixPdf;
using Gtk;
using System.Runtime.Intrinsics;

namespace Majorsilence.PdfWidget.GtkPdf
{
    [System.ComponentModel.ToolboxItem(true)]
    public class PdfWidget : Gtk.Bin, IDisposable
    {
        private PdfDocument pdf;

        private int pageIndex = 0;
        private int pageHeight = 0;
        private float scale = 1f;

        private readonly Gtk.Box vbox1;
        private readonly Gtk.Box hbox1;
        private readonly Gtk.Button SaveButton;
        private readonly Gtk.Button PrintButton;
        private readonly Gtk.Button OpenButton;
        private readonly Gtk.Button ZoomInButton;
        private readonly Gtk.Button ZoomOutButton;
        private readonly Gtk.Button FirstPageButton;
        private readonly Gtk.Button PreviousButton;
        private readonly Gtk.Button NextButton;
        private readonly Gtk.Button LastPageButton;
        private readonly Gtk.SpinButton CurrentPage;
        private readonly Gtk.Label PageCountLabel;
        private readonly Gtk.ScrolledWindow scrolledwindow1;
        private readonly Gtk.Box vboxImages;

        public PdfWidget()
        {
            this.Name = "PdfWidget.PdfWidget";
            this.Visible = false;

            // VBox
            this.vbox1 = new Gtk.Box(Gtk.Orientation.Vertical, 6);
            this.vbox1.Name = "vbox1";

            // HBox
            this.hbox1 = new Gtk.Box(Gtk.Orientation.Horizontal, 6);
            this.hbox1.Name = "hbox1";

            // SaveButton
            this.SaveButton = new Gtk.Button(Gtk.Stock.Save);
            this.SaveButton.CanFocus = true;
            this.SaveButton.Name = "SaveButton";
            this.SaveButton.UseUnderline = true;
            this.SaveButton.Clicked += new System.EventHandler(this.OnSaveButtonClicked);
            this.hbox1.PackStart(this.SaveButton, false, false, 0);

            // PrintButton
            this.PrintButton = new Gtk.Button(Gtk.Stock.Print);
            this.PrintButton.CanFocus = true;
            this.PrintButton.Name = "PrintButton";
            this.PrintButton.UseUnderline = true;
            this.PrintButton.Clicked += new System.EventHandler(this.OnPrintButtonClicked);
            this.hbox1.PackStart(this.PrintButton, false, false, 0);

            // OpenButton
            this.OpenButton = new Gtk.Button(Gtk.Stock.Open);
            this.OpenButton.CanFocus = true;
            this.OpenButton.Name = "OpenButton";
            this.OpenButton.UseUnderline = true;
            this.OpenButton.Clicked += new System.EventHandler(this.OnOpenButtonClicked);
            this.hbox1.PackStart(this.OpenButton, false, false, 0);

            // ZoomInButton
            this.ZoomInButton = new Gtk.Button(Gtk.Stock.ZoomIn);
            this.ZoomInButton.CanFocus = true;
            this.ZoomInButton.Name = "ZoomInButton";
            this.ZoomInButton.UseUnderline = true;
            this.ZoomInButton.Clicked += new System.EventHandler(this.OnZoomInButtonClicked);
            this.hbox1.PackStart(this.ZoomInButton, false, false, 0);

            // ZoomOutButton
            this.ZoomOutButton = new Gtk.Button(Gtk.Stock.ZoomOut);
            this.ZoomOutButton.CanFocus = true;
            this.ZoomOutButton.Name = "ZoomOutButton";
            this.ZoomOutButton.UseUnderline = true;
            this.ZoomOutButton.Clicked += new System.EventHandler(this.OnZoomOutButtonClicked);
            this.hbox1.PackStart(this.ZoomOutButton, false, false, 0);

            // FirstPageButton
            this.FirstPageButton = new Gtk.Button(Gtk.Stock.GotoFirst);
            this.FirstPageButton.CanFocus = true;
            this.FirstPageButton.Name = "FirstPageButton";
            this.FirstPageButton.UseUnderline = true;
            this.FirstPageButton.Clicked += new System.EventHandler(this.OnFirstPageButtonClicked);
            this.hbox1.PackStart(this.FirstPageButton, false, false, 0);

            // PreviousButton
            this.PreviousButton = new Gtk.Button(Gtk.Stock.GoBack);
            this.PreviousButton.CanFocus = true;
            this.PreviousButton.Name = "PreviousButton";
            this.PreviousButton.UseUnderline = true;
            this.PreviousButton.Clicked += new System.EventHandler(this.OnPreviousButtonClicked);
            this.hbox1.PackStart(this.PreviousButton, false, false, 0);

            // NextButton
            this.NextButton = new Gtk.Button(Gtk.Stock.GoForward);
            this.NextButton.CanFocus = true;
            this.NextButton.Name = "NextButton";
            this.NextButton.UseUnderline = true;
            this.NextButton.Clicked += new System.EventHandler(this.OnNextButtonClicked);
            this.hbox1.PackStart(this.NextButton, false, false, 0);

            // LastPageButton
            this.LastPageButton = new Gtk.Button(Gtk.Stock.GotoLast);
            this.LastPageButton.CanFocus = true;
            this.LastPageButton.Name = "LastPageButton";
            this.LastPageButton.UseUnderline = true;
            this.LastPageButton.Clicked += new System.EventHandler(this.OnLastPageButtonClicked);
            this.hbox1.PackStart(this.LastPageButton, false, false, 0);

            // CurrentPage
            this.CurrentPage = new Gtk.SpinButton(0, 999999, 1);
            this.CurrentPage.CanFocus = true;
            this.CurrentPage.Name = "CurrentPage";
            this.CurrentPage.Adjustment.PageIncrement = 10;
            this.CurrentPage.ClimbRate = 1;
            this.CurrentPage.Numeric = true;
            this.CurrentPage.ValueChanged += new System.EventHandler(this.OnCurrentPageValueChanged);
            this.hbox1.PackStart(this.CurrentPage, false, false, 0);

            // PageCountLabel
            this.PageCountLabel = new Gtk.Label();
            this.PageCountLabel.Name = "PageCountLabel";
            this.hbox1.PackStart(this.PageCountLabel, false, false, 0);

            this.vbox1.PackStart(this.hbox1, false, false, 0);

            // ScrolledWindow
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = Gtk.ShadowType.In;

            // Viewport
            Gtk.Viewport viewport = new Gtk.Viewport();
            viewport.ShadowType = Gtk.ShadowType.None;

            // VBoxImages
            this.vboxImages = new Gtk.Box(Gtk.Orientation.Vertical, 6);
            this.vboxImages.Name = "vboxImages";

            viewport.Add(this.vboxImages);
            this.scrolledwindow1.Add(viewport);
            this.vbox1.PackStart(this.scrolledwindow1, true, true, 0);

            this.Add(this.vbox1);
            if (this.Child != null)
            {
                this.Child.ShowAll();
            }
            this.Hide();
            scrolledwindow1.Vadjustment.ValueChanged += HandleScrollChanged;
        }

        private void OnOpenButtonClicked(object sender, System.EventArgs e)
        {
            Gtk.FileChooserDialog fileChooser = new Gtk.FileChooserDialog(
                "Choose the PDF file",
                null,
                Gtk.FileChooserAction.Open,
                "Cancel", Gtk.ResponseType.Cancel,
                "Open", Gtk.ResponseType.Accept);

            Gtk.FileFilter filter = new Gtk.FileFilter();
            filter.Name = "PDF files";
            filter.AddMimeType("application/pdf");
            fileChooser.AddFilter(filter);

            if (fileChooser.Run() == (int)Gtk.ResponseType.Accept)
            {
                string filePath = fileChooser.Filename;
                // Load the PDF file
                LoadPdf(filePath);
            }

            fileChooser.Destroy();
        }

        private void OnZoomInButtonClicked(object sender, System.EventArgs e)
        {
            // Implement the logic to zoom in
            ZoomIn();
        }

        private void OnZoomOutButtonClicked(object sender, System.EventArgs e)
        {
            // Implement the logic to zoom out
            ZoomOut();
        }

        private byte[] BitmapPointerToByteArray(IntPtr bitmapPointer, int length)
        {
            byte[] byteArray = new byte[length];
            System.Runtime.InteropServices.Marshal.Copy(bitmapPointer, byteArray, 0, length);
            return byteArray;
        }

        private void RenderPage()
        {
            var page = pdf.GetPage(this.pageIndex);

            int width = (int)(page.Width * scale);
            pageHeight = (int)(page.Height * scale);
            long length = width * pageHeight * 4;

            // Calculate the stride (row length in bytes) for the Pixbuf
            int stride = width * 4; // 4 bytes per pixel (ARGB32)

            // Render the PDF page into the pixel buffer
            var bitmap = page.Render(new PdfPageRenderConfig()
            {
                Scale = scale,
                Viewport = Vector128.Create(0, 0, (float)width, (float)pageHeight)
            });

            // Convert the bitmap pointer to a byte array
            byte[] bitmapData = BitmapPointerToByteArray(new IntPtr(bitmap.Pointer), stride * pageHeight);

            // Create a Pixbuf from the raw pixel data
            var pixbuf = new Gdk.Pixbuf(Gdk.Colorspace.Rgb, true, 8, width, pageHeight);

            // Copy the rendered pixel buffer into the Pixbuf
            System.Runtime.InteropServices.Marshal.Copy(bitmapData, 0, pixbuf.Pixels, bitmapData.Length);

            Gtk.Image img = new Gtk.Image();
            img.SetSizeRequest(width, pageHeight);
            img.Pixbuf = pixbuf;
            img.Name = "image1";

            vboxImages.Add(img);
        }


        private void RenderPages()
        {
            foreach (Gtk.Widget w in vboxImages.AllChildren)
            {
                vboxImages.Remove(w);
            }

            for (this.pageIndex = 0; this.pageIndex < pdf.Pages; this.pageIndex++)
            {
                RenderPage();
            }

            CurrentPage.Value = CurrentPage.Value + 0;
            this.ShowAll();
        }

        /// <summary>
        /// Loads the pdf.  This is the function you call when you want to display a pdf.
        /// </summary>
        /// <param name='pdfFileName'>
        /// Pdf file name.
        /// </param>
        public void LoadPdf(string pdfFileName)
        {
            // Load the document.
            if (pdfFileName.StartsWith("http://") || pdfFileName.StartsWith("https://"))
            {
                pdfFileName = DownloadPdfAsync(pdfFileName).GetAwaiter().GetResult();
            }
            pdf = PdfDocument.Load(pdfFileName, null);

            PageCountLabel.Text = @"/" + (pdf.Pages - 1).ToString();
            CurrentPage.Value = 0;
            CurrentPage.Adjustment.Upper = pdf.Pages - 1;

            RenderPages();
        }

        /// <summary>
        /// Loads the pdf.  This is the function you call when you want to display a pdf.
        /// </summary>
        /// <param name='pdfFileName'>
        /// Pdf file name.
        /// </param>
        public async Task LoadPdfAsync(string pdfFileName)
        {
            if (pdfFileName.StartsWith("http://") || pdfFileName.StartsWith("https://"))
            {
                pdfFileName = await DownloadPdfAsync(pdfFileName);
            }
            pdf = PdfDocument.Load(pdfFileName, null);
            

            PageCountLabel.Text = @"/" + (pdf.Pages - 1).ToString();
            CurrentPage.Value = 0;
            CurrentPage.Adjustment.Upper = pdf.Pages - 1;

            RenderPages();
        }


        /// <summary>
        /// Raises the next button clicked event.  Only used in single page mode.
        /// </summary>
        /// <param name='sender'>
        /// Sender.
        /// </param>
        /// <param name='e'>
        /// E.
        /// </param>
        protected void OnNextButtonClicked(object sender, System.EventArgs e)
        {
            if (pdf.Pages > (int)CurrentPage.Value)
            {
                CurrentPage.Value = CurrentPage.Value + 1;
            }
        }

        /// <summary>
        /// Raises the previous button clicked event. Only used in single page mode.
        /// </summary>
        /// <param name='sender'>
        /// Sender.
        /// </param>
        /// <param name='e'>
        /// E.
        /// </param>
        protected void OnPreviousButtonClicked(object sender, System.EventArgs e)
        {
            if ((int)CurrentPage.Value > 0)
            {
                CurrentPage.Value = CurrentPage.Value - 1;
            }
        }

        protected void OnFirstPageButtonClicked(object sender, System.EventArgs e)
        {
            CurrentPage.Value = 0;
        }

        protected void OnLastPageButtonClicked(object sender, System.EventArgs e)
        {
            CurrentPage.Value = pdf.Pages;
        }

        private int previousPage = 0;
        protected void OnCurrentPageValueChanged(object sender, System.EventArgs e)
        {

            if (_ignorePageChange)
            {
                // If the page is changed because of scrolling skip everything below.
                // However still set the previous page incase the user starts using the button.
                previousPage = (int)CurrentPage.Value;
                return;
            }

            if (CurrentPage.Value == previousPage)
            {
                return;
            }


            int pageDifference = Math.Abs(previousPage - (int)CurrentPage.Value);
            int moveHeight = ((vboxImages.Spacing + pageHeight) * pageDifference);

            if ((int)CurrentPage.Value == 0)
            {
                scrolledwindow1.Hadjustment.Value = scrolledwindow1.Hadjustment.Lower;
                scrolledwindow1.Vadjustment.Value = scrolledwindow1.Vadjustment.Lower;
            }
            else if ((int)CurrentPage.Value == pdf.Pages)
            {
                scrolledwindow1.Hadjustment.Value = scrolledwindow1.Hadjustment.Lower;
                scrolledwindow1.Vadjustment.Value = scrolledwindow1.Vadjustment.Upper - pageHeight;
            }
            else if (previousPage > (int)CurrentPage.Value)
            { // Move back one page
                scrolledwindow1.Hadjustment.Value = scrolledwindow1.Hadjustment.Lower;
                scrolledwindow1.Vadjustment.Value = scrolledwindow1.Vadjustment.Value - moveHeight;
            }
            else if ((int)CurrentPage.Value > previousPage)
            { // Move forward 1 page
                scrolledwindow1.Hadjustment.Value = scrolledwindow1.Hadjustment.Lower;
                scrolledwindow1.Vadjustment.Value = scrolledwindow1.Vadjustment.Value + moveHeight;
            }


            previousPage = (int)CurrentPage.Value;
        }


        protected void OnPrintButtonClicked(object sender, System.EventArgs e)
        {
            Gtk.PrintOperation print = new Gtk.PrintOperation();
            // Tell the Print Operation how many pages there are
            print.NPages = this.pdf.Pages;
            print.UseFullPage = true;
            print.DefaultPageSetup = new PageSetup();

            print.BeginPrint += new Gtk.BeginPrintHandler(OnBeginPrint);
            print.DrawPage += new Gtk.DrawPageHandler(OnDrawPage);
            print.EndPrint += new Gtk.EndPrintHandler(OnEndPrint);

            // Run the Print Operation and tell it what it should do (Export, Preview, Print, PrintDialog)
            // And provide a parent window if applicable
            var result = print.Run(PrintOperationAction.PrintDialog, null);
        }

        /// <summary>
        /// OnBeginPrint - Load up the Document to be printed and analyze it.
        /// </summary>
        /// <param name="obj">The Print Operation</param>
        /// <param name="args">The BeginPrintArgs passed by the Print Operation</param>
        private void OnBeginPrint(object obj, Gtk.BeginPrintArgs args)
        {
        }

        /// <summary>
        /// OnDrawPage - Draws the Content of each Page to be printed
        /// </summary>
        /// <param name="obj">The Print Operation</param>
        /// <param name="args">The DrawPageArgs passed by the Print Operation</param>
        private void OnDrawPage(object obj, Gtk.DrawPageArgs args)
        {
            // Create a Print Context from the Print Operation
            Gtk.PrintContext context = args.Context;

            // Create a Cairo Context from the Print Context
            Cairo.Context cr = context.CairoContext;

            var page = pdf.GetPage(args.PageNr);

            int width = (int)(page.Width * scale);
            pageHeight = (int)(page.Height * scale);
            long length = width * pageHeight * 4;

            // Calculate the stride (row length in bytes) for the Pixbuf
            int stride = width * 4; // 4 bytes per pixel (ARGB32)

            // Render the PDF page into the pixel buffer
            var bitmap = page.Render(new PdfPageRenderConfig()
            {
                Scale = scale,
                Viewport = Vector128.Create(0, 0, (float)width, (float)pageHeight)
            });

            // Convert the bitmap pointer to a byte array
            byte[] bitmapData = BitmapPointerToByteArray(new IntPtr(bitmap.Pointer), stride * pageHeight);

            // Create a Pixbuf from the raw pixel data
            var pixbuf = new Gdk.Pixbuf(Gdk.Colorspace.Rgb, true, 8, width, pageHeight);

            // Copy the rendered pixel buffer into the Pixbuf
            System.Runtime.InteropServices.Marshal.Copy(bitmapData, 0, pixbuf.Pixels, bitmapData.Length);

            // Draw the Pixbuf to the Cairo context
            Gdk.CairoHelper.SetSourcePixbuf(cr, pixbuf, 0, 0);
            cr.Paint();
        }

        /// <summary>
        /// OnEndPrint - Executed at the end of the Print Operation
        /// </summary>
        /// <param name="obj">The Print Operation</param>
        /// <param name="args">The EndPrintArgs passed by the Print Operation</param>
        private void OnEndPrint(object obj, Gtk.EndPrintArgs args)
        {
        }



        protected void OnSaveButtonClicked(object sender, System.EventArgs e)
        {
            object[] param = new object[4];
            param[0] = "Cancel";
            param[1] = Gtk.ResponseType.Cancel;
            param[2] = "Save";
            param[3] = Gtk.ResponseType.Accept;

            using Gtk.FileChooserDialog fc =
             new Gtk.FileChooserDialog("Save File As",
                                         null,
                                         Gtk.FileChooserAction.Save,
                                         param);


            if (fc.Run() == (int)Gtk.ResponseType.Accept)
            {
                try
                {
                    Uri file = new Uri(fc.Filename);
                    pdf.Save(file.AbsolutePath);
                }
                catch (Exception ex)
                {
                    using Gtk.MessageDialog m = new Gtk.MessageDialog(null, Gtk.DialogFlags.Modal, Gtk.MessageType.Info,
                        Gtk.ButtonsType.Ok, false,
                        "Error Saving Copy of PDF." + System.Environment.NewLine + ex.Message);

                    m.Run();
                    m.Destroy();
                }
            }
            //Don't forget to call Destroy() or the FileChooserDialog window won't get closed.
            fc.Destroy();
        }

        private bool _ignorePageChange = false;
        void HandleScrollChanged(object sender, EventArgs e)
        {
            // vertical value changed
            int currentVAdjustment = (int)scrolledwindow1.Vadjustment.Value;
            int currentPage = (int)CurrentPage.Value;

            int truePageHeight = vboxImages.Spacing + pageHeight;

            int scrollPage = currentVAdjustment / truePageHeight;
            if (scrollPage != currentPage)
            {
                _ignorePageChange = true;
                CurrentPage.Value = scrollPage;
                _ignorePageChange = false;
            }
        }

        private void ZoomIn()
        {
            scale += 0.5f;
            RenderPages();
        }

        private void ZoomOut()
        {
            scale -= 0.5f;
            RenderPages();
        }

        private string workingDir = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "majorsilence", "pdfwidget");

        private async Task<string> DownloadPdfAsync(string url)
        {
            using (HttpClient client = new HttpClient())
            {
                client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3");

                HttpResponseMessage response = await client.GetAsync(url);
                response.EnsureSuccessStatusCode();

                if (!Directory.Exists(workingDir))
                    Directory.CreateDirectory(workingDir);

                string tempFilePath = System.IO.Path.Combine(workingDir, System.IO.Path.GetRandomFileName()+ ".pdf");
                using (FileStream fs = new FileStream(tempFilePath, FileMode.Create, FileAccess.Write, FileShare.None))
                {
                    await response.Content.CopyToAsync(fs);
                    fs.Close();
                }

                return tempFilePath;
            }
        }

        public new void Dispose()
        {
            base.Dispose();
            pdf?.Dispose();

            if (System.IO.Directory.Exists(workingDir))
            {
                try
                {
                    foreach (var file in System.IO.Directory.GetFiles(workingDir))
                    {
                        System.IO.File.Delete(file);
                    }
                }
                catch (Exception ex)
                {
                    // shrug
                }
            }
        }
    }
}
